version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tailadmin:latest
    container_name: tailadmin
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_APP_URL=https://arp.ahmadi98.ir
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s 